# fly.toml app configuration file generated for string-scribe-backend on 2025-11-08T18:09:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'string-scribe-backend'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  ## NOTE: turning autoscaling off for the backend,
  ## because the server takes too long to start up
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"
